# Change these first
owner: NajadaGames # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: Najada FE
    url: https://www.najada.games/
  - name: Najada BE
    url: https://najada.games/api/v1/auth/hello/
  - name: Magic Card Buyer FE
    url: https://magiccardbuyer.eu/
  - name: Magic Card Buyer BE
    url: https://client.magiccardbuyer.eu/search/?q=akroma&page=1

assignees: # Users to assign downtime issues (optional)
  - SukiCZ

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Upptime
  logoUrl: https://www.najada.games/img/logo.svg
  name: najada.games
  introTitle: "Najada.games - Discover the world of board games"
  introMessage: Discover the world of tabletop games! Trading and collectible card games - Magic The Gathering, Pokémon, Yu-Gi-Oh!, Digimon, Flesh and Blood, and more. The best board games and miniature games. Everything conveniently in one place! [**najada.games**](https://www.najada.games/)
  navbar:
    - title: najada.games
      href: https://www.najada.games/
    - title: Upptime
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
